version: '3.8'

services:
  # Backend API
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/stock-tracker-backend:latest
    mem_limit: 512m
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5001
      - JWT_SECRET=${JWT_SECRET}

  # Frontend React application
  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/stock-tracker-frontend:latest
    mem_limit: 256m
    ports:
      - "80:80"
    depends_on:
      - backend 